import { NextResponse } from "next/server";
import { guestListRepository } from "@/lib/repositories/GuestRepository";
import * as xlsx from "xlsx";
import { GuestStatus } from "@/lib/db/models/GuestList";
import { withAuth, AuthenticatedRequest } from "@/lib/authMiddleware";
import { PP } from "@/lib/portalPermissionMatrix";

async function postUploadHandler(req: AuthenticatedRequest) {
  const user = req.user;
  try {
    const formData = await req.formData();
    const file = formData.get("file") as File;
    const isOverride = formData.get("override") === "true"; // frontend flag for confirming overrides

    if (!file) {
      return NextResponse.json({ error: "No file uploaded" }, { status: 400 });
    }

    const todayDate = new Date();
    // Check for existing list today if we are not actively overriding
    if (!isOverride) {
      const existing = await guestListRepository.findByDate(todayDate);
      if (existing) {
        return NextResponse.json(
          {
            error:
              "A guest list has already been uploaded today. Override requested.",
          },
          { status: 409 },
        );
      }
    }

    const arrayBuffer = await file.arrayBuffer();
    let buffer = Buffer.from(arrayBuffer);

    // If it's a CSV mathematically generated by AI, it might have ```csv around it.
    if (file.name.toLowerCase().endsWith(".csv")) {
      let text = buffer.toString("utf-8");
      if (text.trim().startsWith("```")) {
        text = text.replace(/^\s*```[a-zA-Z]*\s*\n/, "");
        text = text.replace(/\n\s*```\s*$/, "");
        buffer = Buffer.from(text, "utf-8");
      }
    }

    const workbook = xlsx.read(buffer, { type: "buffer" });
    const sheetName = workbook.SheetNames[0];
    const sheet = workbook.Sheets[sheetName];

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const rawData = xlsx.utils.sheet_to_json(sheet) as any[];

    // Parse the data based on expected headers matching Mobile app IGuestEntry:
    // Name (mapped to firstName, lastName), Room, Type (status), Arrival
    const parsedGuests = rawData.map(
      (row: Record<string, string | Date | undefined>) => {
        const typeStr = (row["Status"] || "in-house").toString().toLowerCase();

        let status: GuestStatus = "in-house";
        if (typeStr.includes("arrival")) status = "arrival";
        if (typeStr.includes("checkout") || typeStr.includes("checked-out"))
          status = "checked-out";

        const firstName = (row["FirstName"] || "-") as string;
        const lastName = (row["LastName"] || "-") as string;

        return {
          firstName,
          lastName,
          roomNumber: (row["RoomNum"] || row["Room"] || "N/A").toString(),
          status,
          arrivalDate: (
            row["ArrivalDate"] ||
            row["Arrival Date"] ||
            ""
          ).toString(),
          notes: (row["Notes"] || row["notes"] || "").toString(),
        };
      },
    );

    const listData = {
      list_date: todayDate,
      uploader_name: user?.name || "Unknown Admin",
      updatedAt: todayDate,
      lastUpdatedBy: user?.name || "Unknown Admin",
      guests: parsedGuests,
    };

    if (isOverride) {
      await guestListRepository.overrideByDate(todayDate, listData);
    } else {
      await guestListRepository.create(listData);
    }

    return NextResponse.json(
      {
        message: "Guest list uploaded successfully",
        count: parsedGuests.length,
      },
      { status: 201 },
    );
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { error: "Failed to process upload" },
      { status: 500 },
    );
  }
}

export const POST = withAuth(postUploadHandler, [PP.CREATE_GUEST_LIST]);
